### ISSUE TITLE
Filename not given

### ISSUE THREAD

**Issue by Vanuan** [dependents/node-filing-cabinet#71]
I get an error "Filename not given" thrown from `resolve-dependency-path`. I'm using `filing-cabinet@2.1.1`.

Here's a relevant piece of code:

caller:
https://github.com/dependents/node-filing-cabinet/blob/84ad1dbf933bcf2458fcc0e39246fa340ce820e1/index.js#L61-L70

callee:

https://github.com/dependents/node-resolve-dependency-path/blob/6bad609f2cd9f5e740a78b8c2c05007903ed6ca8/index.js#L10-L12

Could you explain how it supposed to work if you supply only one argument to the function that throws when there are less than 3 arguments?

**Comment by Vanuan** [comment]
Stacktrace:

```
✖ Error: filename not given
    at module.exports (/src/node_modules/resolve-dependency-path/index.js:12:26)
    at cabinet (/src/node_modules/filing-cabinet/index.js:70:18)
    at Function.module.exports._getDependencies (/src/node_modules/dependency-tree/index.js:104:20)
    at traverse (/src/node_modules/dependency-tree/index.js:149:37)
    at traverse (/src/node_modules/dependency-tree/index.js:175:20)
    at traverse (/src/node_modules/dependency-tree/index.js:175:20)
    at traverse (/src/node_modules/dependency-tree/index.js:175:20)
    at traverse (/src/node_modules/dependency-tree/index.js:175:20)
    at traverse (/src/node_modules/dependency-tree/index.js:175:20)
    at traverse (/src/node_modules/dependency-tree/index.js:175:20)
```

**Comment by Vanuan** [comment]
Partial debug output:

```
  tree traversing /src/src/components/Tooltip/Tooltip.css +4ms
  precinct options given:  { includeCore: false, type: 'css' } +22ms
  precinct module type:  css +0ms
  detective-postcss found @value with import of css/variables/colors.cssm +0ms
  tree extracted 1 dependencies:  [ 'css/variables/colors.cssm' ] +13ms
  cabinet using generic resolver +17ms
  cabinet found a resolver for .css +5ms
```

**Comment by Vanuan** [comment]
It looks like 2.1.1 is broken.

**Comment by Vanuan** [comment]
And due to this breakage, not only dependency-tree fails, but all projects depending on it. Since this was a patch version change.

**Comment by mrjoelkemp** [comment]
Thanks for reporting! The bug was introduced in 2.0.3 with this commit: https://github.com/dependents/node-filing-cabinet/commit/9f9d37bdadb912682b10fa7146afc171e4352723. 

It was a patch version because the public api of this module didn't change, only the use of the internal resolvers. There was likely a test missing for the generic resolver that didn't catch that I forgot to update that resolve-dependency-path module.

Can you omit css files from being traversed using the filter function of madge in the mean time?

Instead of reverting, I'd like to make the change to the api of resolve-dependency-path, push a major version of that, then bump the version here and release another patch.

**Comment by mrjoelkemp** [comment]
Thanks again for reporting @Vanuan. I pushed a fix to resolve-dependency-path and filing-cabinet. I released a new patch version with the fix.

**Comment by Vanuan** [comment]
Awesome! Thanks.
